import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import { SessionProvider } from "next-auth/react";
//import { Session } from "next-auth";
const inter = Inter({ subsets: ["latin"] });
import { NextAuthProvider } from "@/components/NextAuthProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: // session,
{
  children: React.ReactNode;
  // session?: Session | null;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <div className="flex">
          <NextAuthProvider>
            {" "}
            {/* Added for demonstration purposes, adjust width and other styles as required */}
            <div className="flex-1">{children}</div>
          </NextAuthProvider>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
